export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SET_INVERTER_MANUFACTURER_FILTER ='SET_INVERTER_MANUFACTURER_FILTER';

export const ADD_INVERTER ='ADD_INVERTER';
export const EDIT_INVERTER ='EDIT_INVERTER';
export const CREATE_INVERTER ='CREATE_INVERTER';
export const DELETE_INVERTER ='DELETE_INVERTER';
export const GET_AN_INVERTER ='GET_AN_INVERTER';
export const GET_ALL_INVERTER ='GET_ALL_INVERTER';
export const GET_INVERTERS ='GET_INVERTERS';
export const INVERTER_LOADING ='INVERTER_LOADING';

